### PR TITLE
The package now works

### PR DESCRIPTION
**Pull request by mabasic**
- Fixed form to use GET instead of POST
- Form view can now be published and customized
- Updated readme with correct information

**Question**

Why is the LICENSE named to *2014 Nguyễn Văn Ánh*, and why is the first commit in the repository only 16 days old?

### CODE REVIEW

**Comment by L1lle** [comment]
Thanks a lot. You've been quick. I had some of those items on my list but just started with the initial version. And thanks for the  "vendor publish", good thinking.

**Comment by L1lle** [comment]
Hi @mabasic, Why did you change it from GET to POST requests? This way the entered password will be shown in the browser address bar if it's wrong. I'm not sure if that is the best idea.

**Comment by L1lle** [comment]
Ok, I see your point with "MethodNotAllowedExceptions" being thrown. I had it working with POST on a different site, I will take a look why. for now it should be fine with GET requests.

**Comment by mabasic** [comment]
It works with POST if you have a POST route set up for the same GET route. Eg. GET /about and POST /about

Regarding the password being visible using the GET request.

I need to check this first, but I think that using the built in validation with a custom validation rule should do the trick. That way the password would be only visible in the first GET request.

I will find time to do this in a few days.

P.S. What is the situation with the license for this package?

**Pull request merged**
